// <auto-generated />
using System;
using Api.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20220807203528_First_Migrations")]
    partial class First_Migrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Api.Domain.Entities.CepEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("varchar(60) CHARACTER SET utf8mb4")
                        .HasMaxLength(60);

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("varchar(10) CHARACTER SET utf8mb4")
                        .HasMaxLength(10);

                    b.Property<Guid>("CityId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Number")
                        .HasColumnType("varchar(10) CHARACTER SET utf8mb4")
                        .HasMaxLength(10);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Cep");

                    b.HasIndex("CityId");

                    b.ToTable("Cep");
                });

            modelBuilder.Entity("Api.Domain.Entities.CityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("CodIBGE")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(60) CHARACTER SET utf8mb4")
                        .HasMaxLength(60);

                    b.Property<Guid>("StateId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CodIBGE");

                    b.HasIndex("StateId");

                    b.ToTable("City");
                });

            modelBuilder.Entity("Api.Domain.Entities.StateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Initial")
                        .IsRequired()
                        .HasColumnType("varchar(2) CHARACTER SET utf8mb4")
                        .HasMaxLength(2);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(45) CHARACTER SET utf8mb4")
                        .HasMaxLength(45);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Initial")
                        .IsUnique();

                    b.ToTable("State");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22ffbd18-cdb9-45cc-97b0-51e97700bf71"),
                            CreatedAt = new DateTime(2022, 8, 7, 20, 35, 28, 374, DateTimeKind.Utc).AddTicks(4945),
                            Initial = "AC",
                            Name = "Acre"
                        },
                        new
                        {
                            Id = new Guid("7cc33300-586e-4be8-9a4d-bd9f01ee9ad8"),
                            CreatedAt = new DateTime(2022, 8, 7, 20, 35, 28, 374, DateTimeKind.Utc).AddTicks(4978),
                            Initial = "AL",
                            Name = "Alagoas"
                        },
                        new
                        {
                            Id = new Guid("cb9e6888-2094-45ee-bc44-37ced33c693a"),
                            CreatedAt = new DateTime(2022, 8, 7, 20, 35, 28, 374, DateTimeKind.Utc).AddTicks(4982),
                            Initial = "AM",
                            Name = "Amazonas"
                        },
                        new
                        {
                            Id = new Guid("409b9043-88a4-4e86-9cca-ca1fb0d0d35b"),
                            CreatedAt = new DateTime(2022, 8, 7, 20, 35, 28, 374, DateTimeKind.Utc).AddTicks(4986),
                            Initial = "AP",
                            Name = "Amapá"
                        },
                        new
                        {
                            Id = new Guid("5abca453-d035-4766-a81b-9f73d683a54b"),
                            CreatedAt = new DateTime(2022, 8, 7, 20, 35, 28, 374, DateTimeKind.Utc).AddTicks(4988),
                            Initial = "BA",
                            Name = "Bahia"
                        },
                        new
                        {
                            Id = new Guid("5ff1b59e-11e7-414d-827e-609dc5f7e333"),
                            CreatedAt = new DateTime(2022, 8, 7, 20, 35, 28, 374, DateTimeKind.Utc).AddTicks(4990),
                            Initial = "CE",
                            Name = "Ceará"
                        },
                        new
                        {
                            Id = new Guid("bd08208b-bfca-47a4-9cd0-37e4e1fa5006"),
                            CreatedAt = new DateTime(2022, 8, 7, 20, 35, 28, 374, DateTimeKind.Utc).AddTicks(4992),
                            Initial = "DF",
                            Name = "Distrito Federal"
                        },
                        new
                        {
                            Id = new Guid("c623f804-37d8-4a19-92c1-67fd162862e6"),
                            CreatedAt = new DateTime(2022, 8, 7, 20, 35, 28, 374, DateTimeKind.Utc).AddTicks(4994),
                            Initial = "ES",
                            Name = "Espírito Santo"
                        },
                        new
                        {
                            Id = new Guid("837a64d3-c649-4172-a4e0-2b20d3c85224"),
                            CreatedAt = new DateTime(2022, 8, 7, 20, 35, 28, 374, DateTimeKind.Utc).AddTicks(4996),
                            Initial = "GO",
                            Name = "Goiás"
                        },
                        new
                        {
                            Id = new Guid("57a9e9f7-9aea-40fe-a783-65d4feb59fa8"),
                            CreatedAt = new DateTime(2022, 8, 7, 20, 35, 28, 374, DateTimeKind.Utc).AddTicks(4998),
                            Initial = "MA",
                            Name = "Maranhão"
                        },
                        new
                        {
                            Id = new Guid("27f7a92b-1979-4e1c-be9d-cd3bb73552a8"),
                            CreatedAt = new DateTime(2022, 8, 7, 20, 35, 28, 374, DateTimeKind.Utc).AddTicks(4999),
                            Initial = "MG",
                            Name = "Minas Gerais"
                        },
                        new
                        {
                            Id = new Guid("3739969c-fd8a-4411-9faa-3f718ca85e70"),
                            CreatedAt = new DateTime(2022, 8, 7, 20, 35, 28, 374, DateTimeKind.Utc).AddTicks(5001),
                            Initial = "MS",
                            Name = "Mato Grosso do Sul"
                        },
                        new
                        {
                            Id = new Guid("29eec4d3-b061-427d-894f-7f0fecc7f65f"),
                            CreatedAt = new DateTime(2022, 8, 7, 20, 35, 28, 374, DateTimeKind.Utc).AddTicks(5003),
                            Initial = "MT",
                            Name = "Mato Grosso"
                        },
                        new
                        {
                            Id = new Guid("8411e9bc-d3b2-4a9b-9d15-78633d64fc7c"),
                            CreatedAt = new DateTime(2022, 8, 7, 20, 35, 28, 374, DateTimeKind.Utc).AddTicks(5004),
                            Initial = "PA",
                            Name = "Pará"
                        },
                        new
                        {
                            Id = new Guid("1109ab04-a3a5-476e-bdce-6c3e2c2badee"),
                            CreatedAt = new DateTime(2022, 8, 7, 20, 35, 28, 374, DateTimeKind.Utc).AddTicks(5006),
                            Initial = "PB",
                            Name = "Paraíba"
                        },
                        new
                        {
                            Id = new Guid("ad5969bd-82dc-4e23-ace2-d8495935dd2e"),
                            CreatedAt = new DateTime(2022, 8, 7, 20, 35, 28, 374, DateTimeKind.Utc).AddTicks(5008),
                            Initial = "PE",
                            Name = "Pernambuco"
                        },
                        new
                        {
                            Id = new Guid("f85a6cd0-2237-46b1-a103-d3494ab27774"),
                            CreatedAt = new DateTime(2022, 8, 7, 20, 35, 28, 374, DateTimeKind.Utc).AddTicks(5010),
                            Initial = "PI",
                            Name = "Piauí"
                        },
                        new
                        {
                            Id = new Guid("1dd25850-6270-48f8-8b77-2f0f079480ab"),
                            CreatedAt = new DateTime(2022, 8, 7, 20, 35, 28, 374, DateTimeKind.Utc).AddTicks(5012),
                            Initial = "PR",
                            Name = "Paraná"
                        },
                        new
                        {
                            Id = new Guid("43a0f783-a042-4c46-8688-5dd4489d2ec7"),
                            CreatedAt = new DateTime(2022, 8, 7, 20, 35, 28, 374, DateTimeKind.Utc).AddTicks(5014),
                            Initial = "RJ",
                            Name = "Rio de Janeiro"
                        },
                        new
                        {
                            Id = new Guid("542668d1-50ba-4fca-bbc3-4b27af108ea3"),
                            CreatedAt = new DateTime(2022, 8, 7, 20, 35, 28, 374, DateTimeKind.Utc).AddTicks(5016),
                            Initial = "RN",
                            Name = "Rio Grande do Norte"
                        },
                        new
                        {
                            Id = new Guid("924e7250-7d39-4e8b-86bf-a8578cbf4002"),
                            CreatedAt = new DateTime(2022, 8, 7, 20, 35, 28, 374, DateTimeKind.Utc).AddTicks(5018),
                            Initial = "RO",
                            Name = "Rondônia"
                        },
                        new
                        {
                            Id = new Guid("9fd3c97a-dc68-4af5-bc65-694cca0f2869"),
                            CreatedAt = new DateTime(2022, 8, 7, 20, 35, 28, 374, DateTimeKind.Utc).AddTicks(5020),
                            Initial = "RR",
                            Name = "Roraima"
                        },
                        new
                        {
                            Id = new Guid("88970a32-3a2a-4a95-8a18-2087b65f59d1"),
                            CreatedAt = new DateTime(2022, 8, 7, 20, 35, 28, 374, DateTimeKind.Utc).AddTicks(5022),
                            Initial = "RS",
                            Name = "Rio Grande do Sul"
                        },
                        new
                        {
                            Id = new Guid("b81f95e0-f226-4afd-9763-290001637ed4"),
                            CreatedAt = new DateTime(2022, 8, 7, 20, 35, 28, 374, DateTimeKind.Utc).AddTicks(5024),
                            Initial = "SC",
                            Name = "Santa Catarina"
                        },
                        new
                        {
                            Id = new Guid("fe8ca516-034f-4249-bc5a-31c85ef220ea"),
                            CreatedAt = new DateTime(2022, 8, 7, 20, 35, 28, 374, DateTimeKind.Utc).AddTicks(5026),
                            Initial = "SE",
                            Name = "Sergipe"
                        },
                        new
                        {
                            Id = new Guid("e7e416de-477c-4fa3-a541-b5af5f35ccf6"),
                            CreatedAt = new DateTime(2022, 8, 7, 20, 35, 28, 374, DateTimeKind.Utc).AddTicks(5028),
                            Initial = "SP",
                            Name = "São Paulo"
                        },
                        new
                        {
                            Id = new Guid("971dcb34-86ea-4f92-989d-064f749e23c9"),
                            CreatedAt = new DateTime(2022, 8, 7, 20, 35, 28, 374, DateTimeKind.Utc).AddTicks(5030),
                            Initial = "TO",
                            Name = "Tocantins"
                        });
                });

            modelBuilder.Entity("Api.Domain.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(60) CHARACTER SET utf8mb4")
                        .HasMaxLength(60);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5d397547-dd4b-4839-8084-0dea8338be34"),
                            CreatedAt = new DateTime(2022, 8, 7, 17, 35, 28, 372, DateTimeKind.Local).AddTicks(1916),
                            Email = "admin@gmail.com",
                            Name = "Administrador",
                            UpdatedAt = new DateTime(2022, 8, 7, 17, 35, 28, 372, DateTimeKind.Local).AddTicks(9191)
                        });
                });

            modelBuilder.Entity("Api.Domain.Entities.CepEntity", b =>
                {
                    b.HasOne("Api.Domain.Entities.CityEntity", "City")
                        .WithMany("Ceps")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Domain.Entities.CityEntity", b =>
                {
                    b.HasOne("Api.Domain.Entities.StateEntity", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
